void doPlots_hv()
{
    gROOT->Reset();
    TCanvas* c1 = new TCanvas("c1","c1",800,350);
    c1->Divide(2,1);
    TCanvas* c2 = new TCanvas("c2","c2",800,350);
    c2->Divide(2,1);

    TMultiGraph* mg1 = new TMultiGraph("MiB2","MiB2");
    TMultiGraph* mg2 = new TMultiGraph("MiB3","MiB3");
    TMultiGraph* mg3 = new TMultiGraph("Planacon","Planacon");
    TMultiGraph* mg4 = new TMultiGraph("Roma","Roma");
 
    TGraphErrors* g11 = new TGraphErrors("analyzed_data/Scan1_MiB2_pc_ON.dat");
    g11->SetMarkerStyle(20);
    g11->SetMarkerColor(kRed);
    g11->SetMarkerSize(0.7);
    TGraphErrors* g12 = new TGraphErrors("analyzed_data/Scan2_MiB2_pc_OFF.dat");
    g12->SetMarkerStyle(4);
    g12->SetMarkerColor(kRed);
    g12->SetMarkerSize(0.7);
    TGraphErrors* g13 = new TGraphErrors("analyzed_data/Scan4_MiB2_pc_OFF.dat");
    g13->SetMarkerStyle(26);
    g13->SetMarkerColor(kRed);
    g13->SetMarkerSize(0.7);
 
    TGraphErrors* g21 = new TGraphErrors("analyzed_data/Scan2_MiB3_pc_ON.dat");
    g21->SetMarkerStyle(20);
    g21->SetMarkerColor(kGreen);
    g21->SetMarkerSize(0.7);
    TGraphErrors* g22 = new TGraphErrors("analyzed_data/Scan1_MiB3_pc_OFF.dat");
    g22->SetMarkerStyle(4);
    g22->SetMarkerColor(kGreen);
    g22->SetMarkerSize(0.7);
    TGraphErrors* g23 = new TGraphErrors("analyzed_data/Scan4_MiB3_pc_OFF.dat");
    g23->SetMarkerStyle(26);
    g23->SetMarkerColor(kGreen);
    g23->SetMarkerSize(0.7);

    TGraphErrors* g31 = new TGraphErrors("analyzed_data/Scan2_Planacon_pc_ON.dat");
    g31->SetMarkerStyle(20);
    g31->SetMarkerColor(kBlue);
    g31->SetMarkerSize(0.7);
    TGraphErrors* g32 = new TGraphErrors("analyzed_data/Scan1_Planacon_pc_OFF.dat");
    g32->SetMarkerStyle(4);
    g32->SetMarkerColor(kBlue);
    g32->SetMarkerSize(0.7);
    TGraphErrors* g33 = new TGraphErrors("analyzed_data/Scan3_Planacon_pc_OFF.dat");
    g33->SetMarkerStyle(26);
    g33->SetMarkerColor(kBlue);
    g33->SetMarkerSize(0.7);
    TGraphErrors* g34 = new TGraphErrors("analyzed_data/Scan4_Planacon_pc_OFF.dat");
    g34->SetMarkerStyle(30);
    g34->SetMarkerColor(kBlue);
    g34->SetMarkerSize(0.7);

    TGraphErrors* g41 = new TGraphErrors("analyzed_data/Scan3_Roma2_pc_ON.dat");
    g41->SetMarkerStyle(20);
    g41->SetMarkerColor(9);
    g41->SetMarkerSize(0.7);
    TGraphErrors* g42 = new TGraphErrors("analyzed_data/Scan3_Roma1_pc_OFF.dat");
    g42->SetMarkerStyle(4);
    g42->SetMarkerColor(9);
    g42->SetMarkerSize(0.7);
   
    c1->cd(1);
    mg1->Add(g11);
    mg1->Add(g12);
    mg1->Add(g13);
    mg1->Draw("AP");
    mg1->GetXaxis()->SetTitle("High Voltage [V]");
    mg1->GetXaxis()->SetTitleSize(0.05);
    mg1->GetXaxis()->SetLabelSize(0.04);    
    mg1->GetYaxis()->SetTitle("Efficency");
    mg1->GetYaxis()->SetTitleSize(0.05);        
    mg1->GetYaxis()->SetLabelSize(0.04);
    mg1->GetYaxis()->SetRangeUser(0,1.01);
    gPad->Modified();
    mg1->GetXaxis()->SetRange(1300,3100);
    TLegend* lg1 = new TLegend(0.1,0.55,0.3,0.9); 
    lg1->SetFillColor(kWhite);
    lg1->SetTextSize(0.037);
    lg1->AddEntry(g11,"Scan1 on","P");
    lg1->AddEntry(g12,"Scan2 off","P");
    lg1->AddEntry(g13,"Scan4 off","P");    
    lg1->Draw("same");

    c1->cd(2);
    mg2->Add(g21);
    mg2->Add(g22);
    mg2->Add(g23);
    mg2->Draw("AP");
    mg2->GetXaxis()->SetTitle("High Voltage [V]");
    mg2->GetXaxis()->SetTitleSize(0.05);
    mg2->GetXaxis()->SetLabelSize(0.04);    
    mg2->GetYaxis()->SetTitle("Efficiency");
    mg2->GetYaxis()->SetTitleSize(0.05);        
    mg2->GetYaxis()->SetLabelSize(0.04);
    mg2->GetYaxis()->SetRangeUser(0,1.01);
    gPad->Modified();
    mg2->GetXaxis()->SetRangeUser(1300,3100);
    TLegend* lg2 = new TLegend(0.1,0.55,0.3,0.9); 
    lg1->SetTextSize(0.037);
    lg2->SetFillColor(kWhite);
    lg2->AddEntry(g21,"Scan2 on","P");
    lg2->AddEntry(g22,"Scan1 off","P");
    lg2->AddEntry(g23,"Scan4 off","P");    
    lg2->Draw("same");

    c2->cd(1);
    mg3->Add(g31);
    mg3->Add(g32);
    mg3->Add(g33);
    mg3->Add(g34);
    mg3->Draw("AP");
    mg3->GetXaxis()->SetTitle("High Voltage [V]");
    mg3->GetXaxis()->SetTitleSize(0.05);
    mg3->GetXaxis()->SetLabelSize(0.04);    
    mg3->GetYaxis()->SetTitle("Efficiency");
    mg3->GetYaxis()->SetTitleSize(0.05);        
    mg3->GetYaxis()->SetLabelSize(0.04);
    mg3->GetYaxis()->SetRangeUser(0,1.01);
    TLegend* lg3 = new TLegend(0.1,0.55,0.3,0.9); 
    gPad->Modified();
    mg3->GetXaxis()->SetRange(1300,3100);
    lg3->SetTextSize(0.037);
    lg3->SetFillColor(kWhite);
    lg3->AddEntry(g31,"Scan2 on","P");
    lg3->AddEntry(g32,"Scan1 off","P");
    lg3->AddEntry(g33,"Scan3 off","P");    
    lg3->AddEntry(g34,"Scan4 off","P");    
    lg3->Draw("same");

    c2->cd(2);
    mg4->Add(g41);
    mg4->Add(g42);
    mg4->Draw("AP");
    mg4->GetXaxis()->SetTitle("High Voltage [V]");
    mg4->GetXaxis()->SetTitleSize(0.05);
    mg4->GetXaxis()->SetLabelSize(0.04);    
    mg4->GetYaxis()->SetTitle("Efficiency");
    mg4->GetYaxis()->SetTitleSize(0.05);        
    mg4->GetYaxis()->SetLabelSize(0.04);
    mg4->GetYaxis()->SetRangeUser(0,1.01);
    TLegend* lg4 = new TLegend(0.1,0.55,0.3,0.9); 
    gPad->Modified();
    mg4->GetXaxis()->SetRange(1300,3100);
    lg4->SetTextSize(0.037);
    lg4->SetFillColor(kWhite);
    lg4->AddEntry(g41,"Scan3 on","P");
    lg4->AddEntry(g42,"Scan3 off","P");
    lg4->Draw("same");

    c1->Print("plots/eff_all1.pdf");
    c2->Print("plots/eff_all2.pdf");
}
